export const VtuberIDs = [
    'EliraPendora',
    'PomuRainpuff',
    'FinanaRyugu',
    'Petra_Gurin',
    'Selen_Tatsuki',
    'Rosemi_Lovelock',
    'EnnaAlouette',
    'MillieParfait',
    'ReimuEndou',
    'luca_kaneshiro',
    'ike_eveland',
    'Vox_Akuma',
    'shu_yamino',
    'uki_violeta',
    'fulgur_ovid',
    'Sonny_Brisko',
    'Alban_Knox',
    'MariaMari0nette',
    'KyoKanek0',
    'AsterArcadia',
    'AiaAmare',
    'ScarleYonaguni',
    'RenZott0',
    'd_dropscythe',
    'Ver_Vermillion',
    'MelocoKyoran',
    'KotokaTorahime',
    'HexHaywire',
    'YuQWilson',
    'Tyrant_Vanta',
    'VezaliusBandage',
    'kunainakasato',
    'vbrightshield',
    'claudeclawmark',
]

export const BaseURL = 'https://api.twitter.com/graphql'
export const Authorization = 'Bearer AAAAAAAAAAAAAAAAAAAAANRILgAAAAAAnNwIzUejRCOuH5E6I8xnZz4puTs=1Zv7ttfk8LF81IUq16cHjhLTvJu4FA33AGWWjCpTnA'
export const defaultHeaders = {
    accept: '*/*',
    authorization: Authorization,
    'content-type': 'application/json; charset=utf-8',
    'sec-fetch-dest': 'empty',
    'sec-fetch-mode': 'cors',
    'sec-fetch-site': 'same-site',
    'user-agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/119.0.0.0 Safari/537.36',
    // 'x-twitter-active-user': 'yes',
    // 'x-twitter-client-language': 'zh-cn',
    // Referer: 'https://twitter.com/',
}

export const GraphqlParams = {
    UserByScreenName: 'NimuplG1OB7Fd2btCLdBOw',
    TweetDetail: '4EQGUyO_lbCtGin4PT7MOQ',
    TweetResultByRestId: 'R5zbJueOwsdIMWs3CyE0Iw',
}
