name: Fetch Pinned Tweets
on:
  workflow_dispatch:
  schedule:
    - cron: "5 17 * * 0-3,6"

jobs:
  update_data:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
      - name: Update tweets json for new week
        run: |
          cd ./scripts/
          npm i
          npm run start
      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: update tweets data json
