name: Fetch Pinned Tweets
on:
  workflow_dispatch:
  push:
    branches:
      - main
  # schedule:
  #   - cron: "5 17 * * 0-3,6"

jobs:
  update_data:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Update tweets json for new week
        run: |
          cd .\scripts\
          npm i
          npm run start
      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: update tweets data json
